// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PantryPilot.Api.Data;

#nullable disable

namespace PantryPilot.Api.Migrations
{
    [DbContext(typeof(FoodDbContext))]
    [Migration("20260603091330_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("PantryPilot.Api.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cucumber"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Olives"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lettuce"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Meat"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tomato"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Dough"
                        });
                });

            modelBuilder.Entity("PantryPilot.Api.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Feeds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Feeds = 1,
                            Name = "Burger"
                        },
                        new
                        {
                            Id = 2,
                            Feeds = 1,
                            Name = "Pie"
                        },
                        new
                        {
                            Id = 3,
                            Feeds = 1,
                            Name = "Sandwich"
                        },
                        new
                        {
                            Id = 4,
                            Feeds = 2,
                            Name = "Pasta"
                        },
                        new
                        {
                            Id = 5,
                            Feeds = 3,
                            Name = "Salad"
                        },
                        new
                        {
                            Id = 6,
                            Feeds = 4,
                            Name = "Pizza"
                        });
                });

            modelBuilder.Entity("PantryPilot.Api.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 6,
                            Quantity = 1
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 7,
                            Quantity = 1
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 7,
                            Quantity = 2
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 4,
                            Quantity = 2
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 7,
                            Quantity = 1
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 7,
                            Quantity = 2
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 6,
                            Quantity = 2
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 3,
                            Quantity = 2
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 5,
                            Quantity = 2
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 6,
                            Quantity = 2
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 7,
                            Quantity = 3
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 5,
                            Quantity = 2
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 6,
                            Quantity = 3
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 2,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("PantryPilot.Api.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("PantryPilot.Api.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PantryPilot.Api.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("PantryPilot.Api.Entities.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
